### Build Angular Project ###

FROM node:12-alpine as builder

WORKDIR /usr/src/app

COPY frontend/package*.json ./

RUN npm install

COPY frontend .

RUN npm run build --prod

### Setup NGINX ###

FROM nginx:1.19.6-alpine

COPY nginx/default.conf /etc/nginx/conf.d/

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /usr/src/app/dist/notes-app /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]