apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-notes-app-pv
  labels:
    app: notes-app
    name: db-notes-app-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 256Mi
  hostPath:
    path: /tmp/db
