apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-notes-app-pvc
  labels:
    app: notes-app
    name: db-notes-app-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
